kind: pipeline
type: docker
name: integration

secrets:
  - name: db_connection_string
    type: env

steps:
  - name: code-analysis
    image: boulundeasv/dotnet-sdk-with-java
    commands:
      - export DB_CONNECTION_STRING=$pgconn
      - dotnet sonarscanner begin /k:"easv-devops_KT.OldProject_AY28V3eNEVvRW2O60EAx" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_390fcc672061c853f0cf54c066e3ff4f36206cee" /d:sonar.cs.vscodecoveragexml.reportsPaths=coverage.xml /d:sonar.qualitygate.wait=true
      - dotnet build --no-incremental
      - cd api && dotnet run --no-build & dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
      - dotnet sonarscanner end /d:sonar.token="sqp_390fcc672061c853f0cf54c066e3ff4f36206cee"
