kind: pipeline
type: docker
name: oldProject

steps:
	- name: code-analysis
	  image: boulundeasv/dotnet/sdk-with-java
	  commands:
		  - dotnet sonarscanner begin /k:"easv-devops_KT.OldProject_AY28V3eNEVvRW2O60EAx" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_390fcc672061c853f0cf54c066e3ff4f36206cee"
		  - dotnet build
		  - dotnet sonarscanner end /d:sonar.token="sqp_390fcc672061c853f0cf54c066e3ff4f36206cee"